export default function RandomPage() {
    const ar = ["Phones", "Sleep", "Dreams", "Music", "Movies", "Books", "Travel", "Money", "Food", "Sports",
  "Fashion", "Friendship", "Family", "School", "Homework", "Stress", "Confidence", "Motivation", "Habits", "Hobbies",
  "Exercise", "Gaming", "Internet", "Privacy", "Creativity", "Success", "Failure", "Luck", "Talent", "Discipline",
  "Goals", "Procrastination", "Memories", "Nostalgia", "Humor", "Curiosity", "Leadership", "Competition", "Teamwork", "Kindness",
  "Artificial-intelligence", "Robotics", "Algorithms", "Automation", "Blockchain", "Cryptocurrency", "Bitcoin", "Deepfakes", "Drones", "Nanotechnology",
  "Wearables", "Smartphones", "Streaming", "Podcasts", "Virtual-reality", "Augmented-reality", "Metaverse", "Cybersecurity", "Encryption",
  "Passwords", "Biometrics", "Facial-recognition", "Surveillance", "Cloud-computing", "Quantum-computing", "Semiconductors", "Microchips", "Satellites", "GPS",
  "3D-printing", "Prosthetics", "Exoskeletons", "Automation", "Chatbots", "Algorithms", "Search-engines", "Databases", "Open-source", "Software",
  "Gravity", "Evolution", "Genetics", "DNA", "Mutations", "Viruses", "Bacteria", "Cells", "Proteins", "Enzymes",
  "Neurons", "Hormones", "Immunity", "Vaccines", "Antibiotics", "Placebos", "Evolution", "Extinction", "Fossils",
  "Dinosaurs", "Mammoths", "Primates", "Whales", "Sharks", "Octopuses", "Corals", "Jellyfish", "Ants", "Bees",
  "Spiders", "Bats", "Crows", "Dolphins", "Elephants", "Penguins", "Camouflage", "Bioluminescence", "Regeneration", "Hibernation",
  "Stars", "Planets", "Galaxies", "Nebulas", "Asteroids", "Comets", "Meteors", "Blackholes", "Pulsars", "Quasars",
  "Supernovas", "Exoplanets", "Wormholes", "Relativity", "Cosmology", "Darkmatter", "Darkenergy", "Gravity", "Mars", "Moon",
  "Titan", "Europa", "Enceladus", "Venus", "Mercury", "Jupiter", "Saturn", "Uranus", "Neptune", "Pluto",
  "Astronauts", "Spaceflight", "SpaceX", "Rockets", "Telescopes", "SETI", "Terraforming", "Astrobiology", "Space-mining", "Space-tourism",
  "Memory", "Attention", "Perception", "Dreams", "Phobias", "Habits", "Addiction", "Motivation", "Confidence", "Anxiety",
  "Empathy", "Jealousy", "Narcissism", "Introversion", "Extroversion", "Personality", "Intelligence", "Creativity", "Curiosity", "Conformity",
  "Persuasion", "Manipulation", "Bias", "Stereotypes", "Prejudice", "Placebos", "Déjà-vu", "Nostalgia", "FOMO", "Boredom",
  "Procrastination", "Perfectionism", "Resilience", "Mindfulness", "Meditation", "Body-language", "Eyewitnesses", "False-memories", "Lucid-dreaming", "Flow",
  "Pyramids", "Spartans", "Vikings", "Samurai", "Knights", "Pirates", "Gladiators", "Pharaohs", "Mongols", "Aztecs",
  "Mayans", "Incas", "Romans", "Greeks", "Persians", "Ottomans", "Abbasids", "Vikings", "Crusades", "Renaissance",
  "Enlightenment", "Colonialism", "Imperialism", "Industrialization", "Revolutions", "Exploration", "Silkroad", "Blackdeath", "Plague",
  "Printingpress", "Gunpowder", "Feudalism", "Monarchies", "Democracy", "Propaganda", "Espionage", "Coldwar", "Decolonization", "Archaeology",
  "Antikythera", "Voynich", "Dyatlov", "Roanoke", "Pompeii", "Herculaneum", "Çatalhöyük", "Göbeklitepe", "Mohenjodaro", "Doggerland",
  "Ötzi", "Suttonhoo", "Terracotta", "Nazca", "Stonehenge", "Knossos", "MachuPicchu", "Tenochtitlan", "Petra", "Alexandria",
  "Tartaria", "Baghdad", "Constantinople", "Carthage", "Timbuktu", "Angkor", "Teotihuacan", "Cahokia", "NanMadol", "Derinkuyu",
  "Lindowman", "Lascaux", "Altamira", "Deadsea", "Rosetta", "Library", "Colosseum", "HagiaSophia", "Pompeii", "Bayeux",
  "Forests", "Rainforests", "Deserts", "Glaciers", "Mountains", "Volcanoes", "Earthquakes", "Tsunamis", "Hurricanes", "Tornadoes",
  "Lightning", "Thunder", "Clouds", "Rainbows", "Auroras", "Tides", "Currents", "Erosion", "Droughts", "Floods",
  "Wildfires", "Avalanches", "Sinkholes", "Caves", "Waterfalls", "Rivers", "Lakes", "Islands", "Mangroves", "Wetlands",
  "Permafrost", "Coralreefs", "Kelp", "Plankton", "Mycelium", "Moss", "Lichens", "Pollination", "Migration", "Hibernation",
  "Wolves", "Foxes", "Lions", "Tigers", "Leopards", "Cheetahs", "Bears", "Gorillas", "Chimpanzees", "Orangutans",
  "Koalas", "Pandas", "Sloths", "Kangaroos", "Platypuses", "Beavers", "Otters", "Raccoons", "Meerkats", "Hyenas",
  "Octopuses", "Squid", "Sharks", "Whales", "Dolphins", "Seals", "Walruses", "Penguins", "Flamingos", "Peacocks",
  "Crows", "Ravens", "Owls", "Eagles", "Falcons", "Parrots", "Woodpeckers", "Hummingbirds", "Fireflies", "Mantis",
  "Pizza", "Sushi", "Ramen", "Burgers", "Tacos", "Pasta", "Bread", "Cheese", "Chocolate", "Coffee",
  "Tea", "Spices", "Honey", "Rice", "Noodles", "Kimchi", "Fermentation", "Pickles", "Barbecue", "Hotpot",
  "Wasabi", "Saffron", "Truffles", "Caviar", "Vanilla", "Matcha", "Kombucha", "Tofu", "Tempeh", "Miso",
  "Umami", "Capsaicin", "Gluten", "Lactose", "Sugar", "Salt", "Caffeine", "Preservatives", "Superfoods", "Streetfood",
  "Tennis", "Basketball", "Football", "Soccer", "Baseball", "Hockey", "Golf", "Swimming", "Running", "Cycling",
  "Boxing", "Wrestling", "Fencing", "Archery", "Gymnastics", "Skateboarding", "Surfing", "Skiing", "Snowboarding", "Climbing",
  "Volleyball", "Badminton", "Tabletennis", "Cricket", "Rugby", "Lacrosse", "Rowing", "Diving", "Weightlifting", "Powerlifting",
  "Marathons", "Olympics", "Doping", "Referees", "Coaching", "Mascots", "Stadiums", "Tailgating", "Rivalries", "Dynasties",
  "Hollywood", "Anime", "Manga", "Comics", "Superheroes", "Disney", "Pixar", "Marvel", "DC", "Horror",
  "Comedy", "Thrillers", "Documentaries", "Animation", "Cinematography", "Soundtracks", "Acting", "Directing", "Screenwriting", "Sequels",
  "Remakes", "Franchises", "Fandoms", "Cosplay", "Memes", "Streaming", "Netflix", "YouTube", "TikTok", "Podcasts",
  "Concerts", "Festivals", "Broadway", "Musicals", "Magic", "Illusions", "Stunts", "Special-effects", "Voiceacting", "Storytelling",
  "Hip-hop", "Rock", "Jazz", "Blues", "Classical", "Pop", "Reggae", "Punk", "Metal", "Country",
  "K-pop", "J-pop", "Opera", "Electronic", "House", "Techno", "Dubstep", "Lo-fi", "Vinyl", "Cassette",
  "Sampling", "Autotune", "Producers", "Songwriting", "Lyrics", "Albums", "Mixtapes", "Concerts", "Busking", "DJing",
  "Headphones", "Speakers", "Acoustics", "Earworms", "Musictherapy", "Pitch", "Rhythm", "Harmony", "Melody", "Timbre",
  "Friendship", "Dating", "Family", "Marriage", "Parenting", "Childhood", "Adolescence", "Adulthood", "Community", "Loneliness",
  "Popularity", "Reputation", "Traditions", "Culture", "Language", "Slang", "Manners", "Etiquette", "Generations", "Nostalgia",
  "Urbanization", "Suburbs", "Cities", "Neighborhoods", "Gentrification", "Tourism", "Immigration", "Migration", "Globalization", "Multiculturalism",
  "Volunteering", "Charity", "Activism", "Protests", "Boycotts", "Consumerism", "Minimalism", "Materialism", "Workaholism", "Hustle",
  "Entrepreneurship", "Startups", "Marketing", "Branding", "Advertising", "Leadership", "Management", "Networking", "Negotiation", "Sales",
  "Retail", "Franchises", "Monopolies", "Competition", "Innovation", "Patents", "Trademarks", "Logistics", "Supplychains", "Outsourcing",
  "Freelancing", "Remote-work", "Internships", "Resumes", "Interviews", "Careers", "Recruiting", "Burnout", "Productivity", "Meetings",
  "Subscriptions", "Ecommerce", "Dropshipping", "Influencers", "Merchandising", "Packaging", "Pricing", "Luxury", "Counterfeits", "Thrifting",
  "Budgeting", "Saving", "Investing", "Stocks", "Bonds", "Taxes", "Credit", "Loans", "Mortgages", "Banking",
  "Inflation", "Deflation", "Recession", "Debt", "Interest", "Insurance", "Retirement", "Pensions", "Wealth", "Poverty",
  "Cryptocurrency", "Bitcoin", "NFTs", "Gold", "Cash", "Checks", "ATMs", "Fintech", "Microloans", "Bartering",
  "Compound-interest", "Index-funds", "Dividends", "Speculation", "Bubbles", "Bankruptcy", "Fraud", "Counterfeiting", "Charity", "Economics",
  "Recycling", "Composting", "Deforestation", "Reforestation", "Pollution", "Smog", "Plastics", "Microplastics", "Landfills", "Litter",
  "Conservation", "Biodiversity", "Endangered-species", "Poaching", "Overfishing", "Sustainability", "Renewables", "Solar", "Windpower", "Hydropower",
  "Nuclear", "Geothermal", "Biofuels", "Carbon", "Emissions", "Drought", "Desertification", "Sea-levels", "Acidification", "Ecosystems",
  "Permaculture", "Rewilding", "Greenwashing", "Ecotourism", "Composting", "Rainwater", "Desalination", "Urban-farming", "Vertical-farming", "Electricity",
  "Nutrition", "Protein", "Carbohydrates", "Fats", "Vitamins", "Minerals", "Hydration", "Sleep", "Exercise", "Recovery",
  "Stretching", "Mobility", "Posture", "Breathing", "Meditation", "Mindfulness", "Dentistry", "Vision", "Hearing", "Vaccines",
  "Allergies", "Asthma", "Diabetes", "Obesity", "Insomnia", "Migraines", "Placebos", "Antibiotics", "Probiotics", "Microbiomes",
  "Sunlight", "Circadian", "Caffeine", "Supplements", "Fitness", "Cardio", "Strength", "Endurance", "Flexibility", "Balance",
  "English", "Spanish", "French", "German", "Italian", "Japanese", "Korean", "Chinese", "Arabic", "Hindi",
  "Latin", "Greek", "Sanskrit", "Dialects", "Accents", "Slang", "Idioms", "Etymology", "Bilingualism", "Translation",
  "Writing", "Grammar", "Punctuation", "Typography", "Calligraphy", "Cursive", "Handwriting", "Names", "Nicknames", "Onomatopoeia",
  "Metaphors", "Puns", "Sarcasm", "Irony", "Euphemisms", "Acronyms", "Abbreviations", "Loanwords", "Linguistics", "Phonetics",
  "Painting", "Sculpture", "Photography", "Drawing", "Graffiti", "Architecture", "Fashion", "Design", "Typography", "Calligraphy",
  "Portraits", "Landscapes", "Abstract", "Surrealism", "Impressionism", "Cubism", "Minimalism", "Realism", "Popart", "Baroque",
  "Renaissance", "Dadaism", "Futurism", "Expressionism", "Symbolism", "Mosaics", "Murals", "Ceramics", "Origami", "Pottery",
  "Museums", "Galleries", "Auctions", "Forgery", "Restoration", "Curation", "Patronage", "Arttherapy", "Copyright", "Creativity",
  "Islands", "Borders", "Mountains", "Rivers", "Deserts", "Oceans", "Capitals", "Megacities", "Villages", "Suburbs",
  "Countries", "Provinces", "States", "Territories", "Enclaves", "Exclaves", "Borders", "Maps", "Cartography", "Topography",
  "Population", "Density", "Migration", "Urbanization", "Nomads", "Tourism", "Geopolitics", "Resources", "Climate", "Timezones",
  "Antarctica", "Arctic", "Equator", "Meridians", "Dateline", "Sahara", "Amazon", "Himalayas", "Pacific", "Mediterranean",
  "Déjà-vu", "Synesthesia", "Pareidolia", "Placebo", "Mandela-effect", "Bystander-effect", "Dunning-Kruger", "Impostor-syndrome", "Baader-Meinhof", "Gambler's-fallacy",
  "Ship-of-Theseus", "Trolley-problem", "Butterfly-effect", "Six-degrees", "Uncanny-valley", "Infinite-monkey", "Prisoner's-dilemma", "Tragedy-of-commons", "Broken-windows", "Hawthorne-effect",
  "Dark-patterns", "Clickbait", "Astroturfing", "Sockpuppets", "Bots", "Captcha", "Spam", "Scams", "Hoaxes", "Urban-legends",
  "Cryptids", "Folklore", "Conspiracy", "Mysteries", "Lostmedia", "Backrooms", "Creepypasta", "ARGs", "Puzzles", "Riddles",
  "Watches", "Clocks", "Keys", "Locks", "Umbrellas", "Backpacks", "Sneakers", "Jeans", "Tshirts", "Hats",
  "Glasses", "Mirrors", "Candles", "Pens", "Pencils", "Notebooks", "Coins", "Stamps", "Posters", "Toys",
  "Bicycles", "Skateboards", "Surfboards", "Tents", "Knives", "Tools", "Cameras", "Microphones", "Headphones", "Keyboards",
  "Furniture", "Mattresses", "Pillows", "Doors", "Windows", "Bridges", "Elevators", "Escalators", "Vending-machines", "Arcades",
  "Cars", "Trucks", "Buses", "Trains", "Subways", "Airplanes", "Helicopters", "Bicycles", "Motorcycles", "Scooters",
  "Ships", "Submarines", "Yachts", "Sailboats", "Ferries", "Taxis", "Ridesharing", "Highways", "Roundabouts", "Traffic",
  "Parking", "Tunnels", "Bridges", "Airports", "Railways", "Maglev", "Hyperloop", "Electric-cars", "Autopilot", "Cruises",
  "Roadtrips", "Commutes", "Pedestrians", "Crosswalks", "Traffic-lights", "Licenseplates", "Speedometers", "Fuel", "Batteries", "Engines",
  "Futurism", "Automation", "Colonization", "Terraforming", "Longevity", "Transhumanism", "Cybernetics", "Nanobots", "Robots", "Androids",
  "AI", "Singularity", "Fusion", "Teleportation", "Holograms", "Smartcities", "Megastructures", "Spaceports", "Moonbases", "Marsbases",
  "Cloning", "Geneediting", "Bioprinting", "Cryonics", "Immortality", "Augmentation", "Brain-computers", "Virtual-worlds", "Digital-humans", "Synthetic-biology",
  "Fusion", "Quantum", "Antimatter", "Wormholes", "Dyson-spheres", "Interstellar", "Exoplanets", "Astrobiology", "Space-mining", "Space-elevators",
  "Memes", "Traditions", "Festivals", "Holidays", "Folklore", "Myths", "Legends", "Superstitions", "Rituals", "Symbols",
  "Tattoos", "Piercings", "Fashion", "Cuisine", "Music", "Dance", "Theater", "Cinema", "Literature", "Poetry",
  "Architecture", "Religion", "Languages", "Dialects", "Slang", "Greetings", "Etiquette", "Names", "Storytelling", "Oralhistory",
  "Museums", "Heritage", "Monuments", "Statues", "Souvenirs", "Tourism", "Diaspora", "Identity", "Globalization", "Tradition",
  "Peer-pressure", "Popularity", "Conformity", "Competition", "Cooperation", "Trust", "Loyalty", "Betrayal", "Forgiveness", "Guilt",
  "Shame", "Pride", "Envy", "Anger", "Fear", "Joy", "Grief", "Love", "Friendship", "Attraction",
  "Status", "Reputation", "Identity", "Self-esteem", "Confidence", "Ambition", "Motivation", "Discipline", "Curiosity", "Boredom",
  "Attention", "Distraction", "Focus", "Memory", "Learning", "Decision-making", "Risk-taking", "Impulsivity", "Patience", "Resilience",
  "Debates", "Arguments", "Listening", "Speaking", "Persuasion", "Negotiation", "Storytelling", "Public-speaking", "Body-language", "Eye-contact",
  "Silence", "Tone", "Sarcasm", "Humor", "Compliments", "Apologies", "Rumors", "Gossip", "Misinformation", "Disinformation",
  "Propaganda", "Advertising", "Clickbait", "Headlines", "Journalism", "Podcasts", "Interviews", "Commentary", "Reviews", "Criticism",
  "Debunking", "Fact-checking", "Rhetoric", "Metaphors", "Analogies", "Questions", "Debate", "Dialogue", "Monologues", "Narratives",
  "Minimalism", "Productivity", "Organization", "Decluttering", "Journaling", "Meditation", "Reading", "Cooking", "Gardening", "Camping",
  "Hiking", "Traveling", "Photography", "Volunteering", "Thrifting", "Collecting", "Gaming", "Drawing", "Music", "Writing",
  "Sleep", "Morning-routines", "Night-routines", "Exercise", "Meal-prep", "Budgeting", "Shopping", "Fashion", "Skincare", "Haircare",
  "Pets", "Plants", "Decorating", "DIY", "Crafts", "Baking", "Fishing", "Cycling", "Running", "Swimming",
"Mycorrhizae", "Extremophiles", "Tardigrades", "Archaea", "Prions", "Viroids", "Bacteriophages", "CRISPR", "Telomeres", "Epigenetics",
  "Optogenetics", "Biomimetics", "Gecko-adhesion", "Lotus-effect", "Superconductors", "Metamaterials", "Graphene", "Aerogels", "Photonic-crystals", "Quantum-dots",
  "Neutrinos", "Muons", "Bosons", "Quarks", "Antimatter", "Muon-tomography", "Gravitational-waves", "Cosmic-rays", "Neutron-stars", "Magnetars",
  "Dark-matter", "Vacuum-energy", "Time-dilation", "Entanglement", "Superposition", "Decoherence", "Quantum-tunneling", "Casimir-effect", "Hawking-radiation", "Event-horizons",
  "LiDAR", "Radar", "Sonar", "RFID", "NFC", "Bluetooth", "WiFi", "GPS", "LoRaWAN", "Starlink","Fiberoptics", "OLED", "MicroLED", "E-ink", "Haptics", "Lidar", "SLAM", "Edge-computing", "Serverless", "Containers",
  "Kubernetes", "Git", "APIs", "Webhooks", "CDNs", "Datacenters", "Caching", "Compression", "Encryption", "Hashing",
  "Bitrates", "Codecs", "Raytracing", "Rendering", "Shaders", "Game-engines", "Virtualization", "Firmware", "Bootloaders", "Microcontrollers",
  "Mirages", "Echoes", "Whirlpools", "Quicksand", "Sinkholes", "Bioluminescence", "Fireworks", "Lightning", "Static-electricity", "Magnetism",
  "Sundials", "Hourglasses", "Compasses", "Barometers", "Thermometers", "Metronomes", "Typewriters", "Telegraphs", "Morse-code", "Pigeons",
  "Beekeeping", "Falconry", "Farming", "Irrigation", "Terraces", "Aqueducts", "Canals", "Lighthouses", "Windmills", "Waterwheels",
  "Blacksmithing", "Pottery", "Weaving", "Dyeing", "Papermaking", "Bookbinding", "Glassmaking", "Clockmaking", "Taxidermy", "Cartography",
  "Luck", "Talent", "Hardwork", "Failure", "Success", "Confidence", "Discipline", "Patience", "Kindness", "Honesty",
  "Freedom", "Privacy", "Equality", "Justice", "Responsibility", "Respect", "Courage", "Ambition", "Curiosity", "Creativity",
  "Leadership", "Teamwork", "Competition", "Friendship", "Trust", "Loyalty", "Forgiveness", "Gratitude", "Generosity", "Independence",
  "Change", "Growth", "Failure", "Risk", "Adventure", "Comfort", "Routine", "Balance", "Purpose", "Identity"
    ];

    return (
        <div className="flex-grow flex flex-col justify-center items-center bg-[#f9f5f1]">
            <div className="h-130 w-110 flex flex-col justify-around items-center border-[#b97f55] border-6 bg-[#debba1] mt-20 rounded-3xl">

                <div className="mb-15 mt-15 text-white">Topic: </div>
                <div className="mb-15 mt-15 text-white">Time: </div>
                <div className="mb-15 mt-15 text-white">Modifier:</div>
            </div>
            <div className="h-40 w-90 flex flex-col justify-center items-center">
                    <button className="text-black hover:bg-[#d49263] transition-colors bg-[#b97f55] h-12 w-30 text-white rounded-2xl">Randomize</button>
            </div>

        </div>
    );
}